const NotesActionTypes = {
  TOGGLE_ADD_NOTE_HIDDEN: 'TOGGLE_ADD_NOTE_HIDDEN',
  SAVE_NOTE_START: 'SAVE_NOTE_START',
  SAVE_NOTE_SUCCESS: 'SAVE_NOTE_SUCCESS',
  SAVE_NOTE_FAILURE: 'SAVE_NOTE_FAILURE',
  FETCH_NOTE_START: 'FETCH_NOTE_START',
  FETCH_NOTE_SUCCESS: 'FETCH_NOTE_SUCCESS',
  FETCH_NOTE_FAILURE: 'FETCH_NOTE_FAILURE'
};

export default NotesActionTypes;