const JobsActionTypes = {
  ADD_JOB_START: 'ADD_JOB_START',
  ADD_JOB_SUCCESS: 'ADD_JOB_SUCCESS',
  ADD_JOB_FAILURE: 'ADD_JOB_FAILURE',
  FETCH_JOBS_START: 'FETCH_JOBS_START',
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_FAILURE: 'FETCH_JOBS_FAILURE'
};

export default JobsActionTypes;