const JobsActionTypes = {
  SAVE_JOB_START: 'SAVE_JOB_START',
  SAVE_JOB_SUCCESS: 'SAVE_JOB_SUCCESS',
  SAVE_JOB_FAILURE: 'SAVE_JOB_FAILURE',
  FETCH_JOBS_START: 'FETCH_JOBS_START',
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_FAILURE: 'FETCH_JOBS_FAILURE',
  FETCH_JOB_START: 'FETCH_JOB_START',
  FETCH_JOB_SUCCESS: 'FETCH_JOB_SUCCESS',
  DELETE_JOB_START: 'DELETE_JOB_START',
  DELETE_JOB_SUCCESS: 'DELETE_JOB_SUCCESS',
  DELETE_JOB_FAILURE: 'DELETE_JOB_FAILURE',
  DELETE_ALL_JOBS_START: 'DELETE_ALL_JOBS_START',
  DELETE_ALL_JOBS_SUCCESS: 'DELETE_ALL_JOBS_SUCCESS',
  DELETE_ALL_JOBS_FAILURE: 'DELETE_ALL_JOBS_FAILURE'
};

export default JobsActionTypes;