const UsersActionTypes = {
  SAVE_USER_START: 'SAVE_USER_START',
  SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILURE: 'SAVE_USER_FAILURE',
  SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',
  DELETE_CURRENT_USER_START: 'DELETE_CURRENT_USER_START',
  DELETE_CURRENT_USER_SUCCESS: 'DELETE_CURRENT_USER_SUCCESS',
  DELETE_CURRENT_USER_FAILURE: 'DELETE_CURRENT_USER_FAILURE',
  RESET_USER_ERRORS: 'RESET_USER_ERRORS'
};

export default UsersActionTypes;