const UsersActionTypes = {
  SAVE_USER_START: 'SAVE_USER_START',
  SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
  SAVE_USER_FAILURE: 'SAVE_USER_FAILURE',
  SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',
  REMOVE_CURRENT_USER: 'REMOVE_CURRENT_USER'
};

export default UsersActionTypes;